### ISSUE TITLE
TeX Live 2020

### ISSUE THREAD

**Issue by DavidLuptak** [michal-h21/biblatex-iso690#79]
The deadline for TeX Live 2020 code freeze is quickly approaching (March 15) and it would be nice to release v0.4.0 beforehand. I can identify at least the following things that should be done:

- [x] implement #75 (dates)
- [ ] ~~finish translations~~
  - [x] ongoing PR #77 -- Bulgarian
  - [x] ongoing PR #78 -- French
  - [ ] ~~would @Crissov like to help with German translation? The information are on the wiki page [Translation Guideline](https://github.com/michal-h21/biblatex-iso690/wiki/Translation-Guideline#the-key-director--bydirector).~~
  - [ ] ~~I don't know who could help with Polish translation..~~
- [x] update documentation for the recent changes
- [x] online medium type for theses / dissertations #80 
- [x] urldate #81 
- [x] update documentation

Then we can upload the package to CTAN hopefully.

**Comment by DavidLuptak** [comment]
Plan for TeX Live 2020 prolonged the final updates from CTAN to 27th March

![Screenshot_2020-03-22 TeX Live - TeX Users Group](https://user-images.githubusercontent.com/11637888/77257209-35ed3b80-6c73-11ea-9ad7-4faaa05d4c2b.png)

https://www.tug.org/texlive/

**Comment by DavidLuptak** [comment]
Hi all, last couple of commits from me were changes mainly to the documentation, bib file, or minor changes to the code mark-up.

I prepared the bundle for the next release `v0.4.0` in 226699eaa48865fb3809b8391481ee09c9969eec.

I uploaded also rendered documentation in PDF if you want to have a look at that one (https://github.com/michal-h21/biblatex-iso690/blob/master/biblatex-iso690.pdf).

Not all of the items on the list mentioned above are checked (missing German and Polish translations), but that's no show-stopper for a release. If you concern about something that should be done additionally to this release, just give me a shout, otherwise @michal-h21 can upload the package to CTAN, finally.

**Comment by moewew** [comment]
There are some uses of
```latex
(see~\parencite{gorki1955artamonovs})
```
in the documentation that could probably be
```latex
\parencite[see][]{gorki1955artamonovs}
```

Other than that things look good to me. (But note that I'm not completely up to speed here.)

**Comment by DavidLuptak** [comment]
> The creator's name and the year of publication of the resource cited are given in the text in a name and date system. If the creator's name occurs naturally in the text, the year follows in parentheses, but if not, both name and year are in parentheses. In citations to particular parts of an information resource, the location of that part (e.g. page number) may be given after the year within the parentheses.

Based on this excerpt from the standard, this actually does not exclude that in the parentheses couldn't be also something else than name and date only, however it might be slightly against what we write in 2.3.2 about this usage and might not serve as a good example indeed. But I reduced a number of parentheses in this case anyway, good catch (I haven't used this `prenote` and `postnote` features of cite command so much).

**Comment by michal-h21** [comment]
I hope that it is only some issue on my system, but I get an error when I try to compile the documentation:

```
(/usr/local/texlive/2019/texmf-dist/tex/latex/biblatex/lbx/czech.lbx
File: czech.lbx 2019/12/01 v3.14 biblatex localization (PK/MW)
)
Package biblatex Info: Trying to load language 'czech'...
Package biblatex Info: ... file 'czech.lbx' found.

(/usr/local/texlive/2019/texmf-dist/tex/latex/biblatex/lbx/czech.lbx
File: czech.lbx 2019/12/01 v3.14 biblatex localization (PK/MW)
))

! Package biblatex Error: Patching 'babel' package failed.

See the biblatex package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
```

Does anybody else experience this issue?

**Comment by moewew** [comment]
@michal-h21 That will be fixed in the next `biblatex` version (most definitely not released in time for TeX live 2020), see https://tex.stackexchange.com/q/529984/35864. For Slovak you will also need https://tex.stackexchange.com/q/532972/35864.

**Comment by michal-h21** [comment]
@moewew ah thanks. I suspected that the issue will be something similar :)

**Comment by DavidLuptak** [comment]
We have released https://github.com/michal-h21/biblatex-iso690/releases/tag/v0.4.0 :tada:
